name: 'Sync from upstream'

on:
  schedule:
    # scheduled at 06:00 for GMT+8
    - cron:  '0 22 * * *'
  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    strategy:
      fail-fast: false
      matrix:
        syncup:
          - from: 'master'
            to: 'master'
          - from: '1.1'
            to: '1.1'
          - from: '2.2.0'
            to: '2.2.0'
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.syncup.to }}
        persist-credentials: false

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: ${{ matrix.syncup.to }}
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: ${{ matrix.syncup.from }}
        upstream_sync_repo: milvus-io/milvus
        # upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
        git_config_pull_rebase: true
        test_mode: false

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."

    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."

    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
  
